# check it first with http://yaml-online-parser.appspot.com/!
development:
  sessions:
    default:
      uri: mongodb://development:development@ds045157.mongolab.com:45157/quacking_nemesis_development
      options:
        safe: true
test:
  sessions:
    default:
      uri: mongodb://test:test@ds045157.mongolab.com:45157/quacking_nemesis_test
      options:
        safe: true
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
# disabled due parsing errors while using erb inside.
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true